apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-smart-house-ai-backend
  namespace: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cf-smart-house-ai-backend
  template:
    metadata:
      labels:
        app: cf-smart-house-ai-backend
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - --protocol
            - http2
            - --url
            - http://smart-house-ai-backend.apps.svc.cluster.local:80
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
