apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-health-chat-api
  namespace: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cf-health-chat-api
  template:
    metadata:
      labels:
        app: cf-health-chat-api
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - --protocol
            - http2
            - --url
            - http://health-chat-api.apps.svc.cluster.local:80
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
